In [11]:
import numpy as np

In [2]:
x = np.arange(0,20,2)

In [3]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
X = x.reshape((2,-1))

In [5]:
X

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [13]:
a = np.array([i for i in range(1,6)])

In [14]:
a

array([1, 2, 3, 4, 5])

In [15]:
b = np.concatenate((X,a.reshape((1,-1))))

In [16]:
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [ 1,  2,  3,  4,  5]])

In [2]:
a = np.array([[1,2],[3,4]])

In [3]:
b = np.array([[5,6]])

In [4]:
a.shape

(2, 2)

In [5]:
b.shape

(1, 2)

In [6]:
c = np.concatenate((a,b))

In [7]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
d = np.concatenate((a,b.T),axis=1)

In [10]:
d

array([[1, 2, 5],
       [3, 4, 6]])

In [12]:
A= np.arange(20).reshape((4,-1))

In [13]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
A1,A2 = np.split(A,[2])

In [15]:
A1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
A2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
A1,A2 = np.split(A,[2],axis =1 )

In [18]:
A1

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [19]:
A2

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])