In [1]:
import numpy as np

In [4]:
arr = np.linspace(0,20,num=15)

In [15]:
matrix = arr.reshape((3,-1))
matrix

array([[ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571],
       [ 7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286],
       [14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ]])

In [8]:
arr.ndim

1

In [9]:
matrix.ndim

2

In [10]:
arr.shape

(15,)

In [11]:
matrix.shape

(3, 5)

In [12]:
arr.size

15

In [13]:
matrix.size

15

In [14]:
matrix[0,3]

4.285714285714286

In [19]:
arr[:4]

array([0.        , 1.42857143, 2.85714286, 4.28571429])

In [20]:
arr[::2]

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [21]:
matrix[:1,:2]

array([[0.        , 1.42857143]])