In [2]:
import numpy as np

In [3]:
np.__version__

'1.14.3'

### python list 特点
#### 数据类型可以不同，
#### list中存放的是引用
#### 性能不高

In [7]:
L = [ i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
L[0] = 'A'

In [11]:
L

['A', 1, 2, 3, 4, 5, 6, 7, 8, 9]

### python array 特点
#### 存放数据必须相同
#### 矩阵、向量方面的操作不方便

In [12]:
import array

In [13]:
#其中 ‘i’为typecode，定义了数据类型
arr = array.array('i',[i for i in range(10)])

In [14]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[4] = 8

In [16]:
arr

array('i', [0, 1, 2, 3, 8, 5, 6, 7, 8, 9])

In [17]:
# 不能存放不同类型的数据
arr[4] ='8'

TypeError: an integer is required (got type str)

### numpy特点
#### 只能存放相同类型

In [18]:
nparr = np.array([i for i in range(10)])

In [19]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
nparr.dtype

dtype('int32')

In [21]:
nparr[3] = 3.4

In [22]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
nparr.dtype

dtype('int32')

In [24]:
npFloatArr = np.array([ i for i in range(10)],dtype=np.float)

In [25]:
npFloatArr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])