In [26]:
import numpy as np
from math import sqrt

In [27]:
X = np.random.rand(20)

In [28]:
X = X.reshape(-1,2)

In [29]:
X

array([[0.16000003, 0.3995265 ],
       [0.01355527, 0.1718601 ],
       [0.05859112, 0.79643262],
       [0.02788801, 0.99739989],
       [0.88311764, 0.31654197],
       [0.81364766, 0.71256708],
       [0.8025574 , 0.80920073],
       [0.27810903, 0.60743741],
       [0.60404572, 0.40682305],
       [0.27549702, 0.33506232]])

In [30]:
x = [0.2,0.6]

In [32]:
distance = [ sqrt(np.sum((i-x)**2)) for i in X]

In [33]:
distance

[0.2044251060259043,
 0.46697474666842753,
 0.24203769395177385,
 0.43306952337405136,
 0.739593243499804,
 0.6238868435534433,
 0.6378403940943399,
 0.07846232101974351,
 0.4478507363578499,
 0.2754846138913189]

In [35]:
distanceSortIndex = np.argsort(distance)

In [36]:
distanceSortIndex

array([7, 0, 2, 9, 3, 8, 1, 5, 6, 4], dtype=int64)

In [52]:
k = 6

In [53]:
y = np.random.randint(0,3,10)

In [54]:
y

array([2, 2, 0, 2, 2, 2, 1, 2, 0, 0])

In [55]:
topK_y = [y[i] for i in distanceSortIndex[:k]]

In [56]:
topK_y

[2, 2, 0, 0, 2, 0]

In [57]:
from collections import Counter

In [58]:
voters = Counter(topK_y)
voters

Counter({2: 3, 0: 3})

In [59]:
a = voters.most_common(1)[0][0]

In [60]:
a

2